version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - /home/Grow-Desenvolvimento/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "contato@growdesenvolvimento.com.br"
      PGADMIN_DEFAULT_PASSWORD: "grow"
    ports:
      - "4000:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
